dep = dict()
dep['Vaccinium macrocarpon']   = 0 # cranberry
dep['Actinidia deliciosa']     = 0 # kiwi
dep['Citrus paradisi']         = 0 # grapefruit
dep['Coffea arabica']          = 0 # coffee
dep['Coffea canephora']        = 0 # coffee
dep['Annona squamosa atemoya'] = 0 # cherimoya, atemoya
dep['Malus domestica']         = 0 # apple
dep['Cucumis melo']            = 0 # melon
dep['Solanum lycopersicum']    = 0 # tomato
dep['Capsicum annuum']         = 0 # peppers, cayenne peppers
dep['Citrullus lanatus']       = 0 # watermelon
dep['Passiflora edulis']       = 0 # passion fruit
dep['Fagopyrum esculentum']    = 0 # buckwheat
dep['Mangifera indica']        = 0 # mango
dep['Vicia faba']              = 0 # broad bean
dep['Coffea arabica/robusta']  = 0 # coffee
dep['Brassica napus']          = 0 # rapeseed
dep['Bixa orellana']           = 0 # achiote
dep['Prunus dulcis']           = 0 # almond
dep['Trifolium pratense']      = 0 # red clover
dep['Cajanus cajan']           = 0 # pigeon pea
dep['Fragaria x ananassa']     = 0 # strawberry
dep['Helianthus annuus']       = 0 # sunflower
dep['Vaccinium corymbosum']    = 0 # highbush blueberry
dep['Pyrus communis']          = 0 # pear
dep['Brassica rapa']           = 0 # turnip
dep['Prunus avium']            = 0 # cherry
dep['Cucurbita pepo']          = 0 # pumpkin
dep['Anacardium occidentale']  = 0 # cashew nut
dep['Gossypium hirsutum']      = 0 # cotton
dep['Malpighia emarginata']    = 0 # acerola cherry
dep['Allium porrum']           = 0 # Leek
dep['Vaccinium meridionale']   = 0 # andean blueberry
dep['Annona squamosa']         = 0 # cherimoya
dep['Malus pumila']            = 0 # apple
dep['Prunus cerasus']          = 0 # sour cherry
dep['Rubus idaeus']            = 0 # raspberry
dep['Abelmoschus esculentus']  = 0 # okra
dep['Cucumis sativus']         = 0 # cucumber
dep['Lagenaria siceraria']     = 0 # calabash
dep['Luffa acutangula']        = 0 # angled luffa
dep['Momordica charantia']     = 0 # bitter melon
dep['Persea americana']        = 0 # avocado
dep['Citrus limon']            = 0 # lemon
dep['Phaseolus vulgaris L.']   = 0 # common bean
dep['Macadamia integrifolia']  = 0 # macadamia
dep['Psidium guajava']         = 0 # common guava