dep = dict()
dep['Vaccinium macrocarpon'] = 'high' # cranberry
dep['Actinidia deliciosa'] = 'essential'   # kiwi
dep['Citrus paradisi'] = 'low'       # grapefruit
dep['Coffea arabica'] = 'moderate' # coffee
dep['Coffea canephora'] = 'moderate' # coffee
dep['Annona squamosa atemoya'] = 'essential'  # cherimoya, atemoya
dep['Malus domestica'] = 'high' # apple
dep['Cucumis melo'] = 'essential' # melon
dep['Solanum lycopersicum'] = 'low' # tomato
dep['Capsicum annuum'] = 'low' # peppers, cayenne peppers
dep['Citrullus lanatus'] = 'essential' # watermelon
dep['Passiflora edulis'] = 'essential' # passion fruit
dep['Fagopyrum esculentum'] = 'high' # buckwheat
dep['Mangifera indica'] = 'high' # mango
dep['Vicia faba'] = 'moderate' # broad bean
dep['Coffea arabica/robusta'] = 'moderate' # coffee
dep['Brassica napus'] = 'moderate' # rapeseed
dep['Bixa orellana'] = 'unknown' # achiote
dep['Prunus dulcis'] = 'high' # almond
dep['Trifolium pratense'] = 'unknown' # red clover
dep['Cajanus cajan'] = 'low' # pigeon pea
dep['Fragaria x ananassa'] = 'moderate' # strawberry
dep['Helianthus annuus'] = 'moderate' # sunflower
dep['Vaccinium corymbosum'] = 'high' # 'high'bush blueberry
dep['Pyrus communis'] = 'high' # pear
dep['Brassica rapa'] = 'high' # turnip
dep['Prunus avium'] = 'high' # cherry
dep['Cucurbita pepo'] = 'essential' # pumpkin
dep['Anacardium occidentale'] = 'high' # cashew nut
dep['Gossypium hirsutum'] = 'moderate' # cotton
dep['Malpighia emarginata'] = 'unknown' # acerola cherry
dep['Allium porrum'] = 'unknown' # Leek
dep['Vaccinium meridionale'] = 'unknown' # andean blueberry
dep['Annona squamosa'] = 'essential'  # cherimoya
dep['Malus pumila'] = 'high' # apple
dep['Prunus cerasus'] = 'high' # sour cherry
dep['Rubus idaeus'] = 'high' # raspberry
dep['Abelmoschus esculentus'] = 'moderate' # okra
dep['Cucumis sativus'] = 'high' # cucumber
dep['Lagenaria siceraria'] = 'unknown' # calabash
dep['Luffa acutangula'] = 'unknown' # angled luffa
dep['Momordica charantia'] = 'unknown' # bitter melon
dep['Persea americana'] = 'high' # avocado
dep['Citrus limon'] = 'low' # lemon
dep['Phaseolus vulgaris L.'] = 'low' # common bean
dep['Macadamia integrifolia'] = 'essential' # macadamia
dep['Psidium guajava'] = 'high' # common guava
