"""
Crops' pollinators dependency (0-1)
"""

dep = dict()
dep['Vaccinium macrocarpon'] = 0.65 # cranberry
dep['Actinidia deliciosa'] = 0.95   # kiwi
dep['Citrus paradisi'] = 0.05       # grapefruit
dep['Coffea arabica'] = 0.25 # coffee
dep['Coffea canephora'] = 0.25 # coffee
dep['Annona squamosa atemoya'] = 0.95  # cherimoya, atemoya
dep['Malus domestica'] = 0.65 # apple
dep['Cucumis melo'] = 0.95 # melon
dep['Solanum lycopersicum'] = 0.05 # tomato
dep['Capsicum annuum'] = 0.05 # peppers, cayenne peppers
dep['Citrullus lanatus'] = 0.95 # watermelon
dep['Passiflora edulis'] = 0.95 # passion fruit
dep['Fagopyrum esculentum'] = 0.65 # buckwheat
dep['Mangifera indica'] = 0.65 # mango
dep['Vicia faba'] = 0.25 # broad bean
dep['Coffea arabica/robusta'] = 0.25 # coffee
dep['Brassica napus'] = 0.25 # rapeseed
dep['Bixa orellana'] = None # achiote
dep['Prunus dulcis'] = 0.65 # almond
dep['Trifolium pratense'] = None # red clover
dep['Cajanus cajan'] = 0.05 # pigeon pea
dep['Fragaria x ananassa'] = 0.25 # strawberry
dep['Helianthus annuus'] = 0.25 # sunflower
dep['Vaccinium corymbosum'] = 0.65 # highbush blueberry
dep['Pyrus communis'] = 0.65 # pear
dep['Brassica rapa'] = 0.65 # turnip
dep['Prunus avium'] = 0.65 # cherry
dep['Cucurbita pepo'] = 0.95 # pumpkin
dep['Anacardium occidentale'] = 0.65 # cashew nut
dep['Gossypium hirsutum'] = 0.25 # cotton
dep['Malpighia emarginata'] = None # acerola cherry
dep['Allium porrum'] = None # Leek
dep['Vaccinium meridionale'] = None # andean blueberry
dep['Annona squamosa'] = 0.95  # cherimoya
dep['Malus pumila'] = 0.65 # apple
dep['Prunus cerasus'] = 0.65 # sour cherry
dep['Rubus idaeus'] = 0.65 # raspberry
dep['Abelmoschus esculentus'] = 0.25 # okra
dep['Cucumis sativus'] = 0.65 # cucumber
dep['Lagenaria siceraria'] = None # calabash
dep['Luffa acutangula'] = None # angled luffa
dep['Momordica charantia'] = None # bitter melon
dep['Persea americana'] = 0.65 # avocado
dep['Citrus limon'] = 0.05 # lemon
dep['Phaseolus vulgaris L.'] = 0.05 # common bean
dep['Macadamia integrifolia'] = 0.95 # macadamia
dep['Psidium guajava'] = 0.65 # common guava
